on:
  push:
    branches:
      - '*/'
      - '**/'
      - '!main'
  pull_request:
    branches:
      - main


env:
  CREDS: ${{ secrets.GCP_CREDS }}
  PROJ_ID: ${{ secrets.GCP_PROJ_ID }}
  REPO: ${{ secrets.GAR_REPO }}
  TESTS: ./tests/systems


jobs:
  birdsnest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        python-version: '3.10.4'
        architecture: 'x64'
    - run: |
        python -m pip install .

    - name: Authenticate to GGP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: $CREDS
    
    - name: GAR Login
      uses: docker/login-action@v2
      with:
        registry: '${{ env.GAR_REGION }}-docker.pkg.dev'
        username: somename
        password: $CREDS
