on:
  push:
    branches:
      - '*/'
      - '**/'
      - '!main'


env:
  TESTS: ./tests/systems


jobs:
  argonest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        python-version: '3.10.4'
        architecture: 'x64'
    - run: |
        python -m pip install .
    
    - name: GAR Login
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.GCP_REGION }}-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCP_CREDS }}

    - name: Build & Push Test Many Dev
      if: github.event_name == 'push'
      run: >
        forge images
        --buildargs '{"_NINJATO_": "0", "_JELLY_": "1", "_PB_": "2"}'
        --env dev
        --gitsha ${{ github.sha }}
        --parent-dir $TESTS/manybargs

    - name: Build & Push Test Dev
      if: github.event_name == 'push'
      run: >
        forge image
        --buildargs '{"_JELLY_": "0", "_PB_": "1"}'
        --env dev
        --gitsha ${{ github.sha }}
        --where $TESTS/bargs
